### ISSUE TITLE
ARKitDemoPlayground doesn't work on the iOS 11 GM

### ISSUE THREAD

**Issue by mhanlon** [mhanlon/ARKitDemoPlayground#1]
I'm looking into it, but the playground doesn't seem to work on the iOS GM.

Stay tuned...

**Comment by algal** [comment]
Au contraire. Works for me! 

I just realized I can even load these playgrounds onto my iPad directly using Working Copy.  Pretty cool!

**Comment by mhanlon** [comment]
You're right, of course, meant to update this issue... :)
